name: ðŸš€ Deploy automÃ¡tico por FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Subida vÃ­a FTP
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Subir al servidor DonWeb vÃ­a FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          ftp-server: ${{ secrets.FTP_HOST }}
          ftp-username: ${{ secrets.FTP_USER }}
          ftp-password: ${{ secrets.FTP_PASS }}
          local-dir: ./
