name: Deploy a DonWeb (FTP)

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name:  Implementar vía FTP
    runs-on: ubuntu-latest

    steps:
      - name:  Clonar el repo
        uses: actions/checkout@v3

      - name:  Subir al servidor vía FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          server-dir: /public_html/
