name: Deploy a DonWeb (FTP)

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: ðŸš€ Deploy vÃ­a FTP
    runs-on: ubuntu-latest

    steps:
      - name: ðŸ“¥ Clonar el repo
        uses: actions/checkout@v3

      - name: ðŸ“¤ Subir al servidor vÃ­a FTP
        uses: SamKirkland/FTP-Deploy-Action@v4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USER }}
          password: ${{ secrets.FTP_PASS }}
          server-dir: /public_html/
